### ISSUE TITLE
Resources related to Data science 

### ISSUE THREAD

**Issue by Thuva4** [Thuva4/Resources#3]
Add resources related to data science.

**Comment by asi7296** [comment]
I'd like to fork this repo and add a few resources related to data science, if that's alright?

**Comment by abdullah-K** [comment]
I would like to add a few resources for Data Science in this list.

**Comment by jedsmithobd** [comment]
#25 I added a few data science resources. 

@abdullah-K looking forward to seeing what resources you add.
